// <auto-generated />
namespace AracKiralamaOtomasyonu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AracKiralama : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AracKiralama));
        
        string IMigrationMetadata.Id
        {
            get { return "202205221713490_AracKiralama"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
